### ISSUE TITLE
Parse issue

### ISSUE THREAD

**Issue by DeMoorJasper** [jihchi/parcel-plugin-bucklescript#1]
I see you've based your plugin on mine, would like to point u to this commit, because my parse function contained a bug that totally ignored post-transforming with babel.

https://github.com/DeMoorJasper/parcel-plugin-svelte/commit/c4304e02ce12682036cbf08d1ed6188d4ee7b3e3

**Comment by jihchi** [comment]
@DeMoorJasper Thank you!
